// Phase A — role wallets, funding, on-chain registration, relay env.
//
// Parties (each a distinct on-chain identity, for a faithful cost breakdown):
//   customer-main  = deployer (does the KS deposit; the only linkable step)
//   customer-burner= fresh, KS-funded (places the order; unlinked to main)
//   venue          = operator+signer+payout (registers, cosigns pickup, paid)
//   driver         = registers, bids, cosigns, paid
//   relay          = the venue-node relay account (pays gas for gasless settle)
import { ethers } from "ethers";
import fs from "fs";
import path from "path";
import {
  ROOT, provider, book, env, loadState, saveState, record, leanGas, fmt, eth,
} from "./e2e-lib.mjs";

const VENUE_LAT = 37_774_900; // San Francisco
const VENUE_LON = -122_419_400;

const FUND = {
  venue: eth("60"), // gas for registerVenue + vault.withdraw
  driver: eth("60"), // gas for register + placeBid + vault.withdraw
  relay: eth("600"), // 500M-weight settlement calls reserve ~500 PAS each
};

async function main() {
  const prov = provider();
  const b = book();
  const deployer = new ethers.Wallet(env("DEPLOYER_PRIVATE_KEY"), prov);
  const st = loadState();
  st.chainId = Number((await prov.getNetwork()).chainId);
  st.addresses = b;
  st.deployer = deployer.address;
  st.coords = { venueLat: VENUE_LAT, venueLon: VENUE_LON };

  console.log(`deployer (customer-main): ${deployer.address}  ${fmt(await prov.getBalance(deployer.address))} PAS`);

  // 1. Role wallets (persist so the run is resumable) ──────────────────────────
  st.wallets = st.wallets || {};
  for (const role of ["venue", "driver", "relay", "burner"]) {
    if (!st.wallets[role]) {
      const w = ethers.Wallet.createRandom();
      st.wallets[role] = { address: w.address, privateKey: w.privateKey };
      console.log(`   + generated ${role}: ${w.address}`);
    }
  }
  saveState(st);
  const V = new ethers.Wallet(st.wallets.venue.privateKey, prov);
  const D = new ethers.Wallet(st.wallets.driver.privateKey, prov);
  const R = st.wallets.relay.address;

  // 2. Fund gas-bearing role wallets from the deployer ─────────────────────────
  console.log(`\n2. Funding role wallets (gas floats) from deployer`);
  for (const [role, amt] of [["venue", FUND.venue], ["driver", FUND.driver], ["relay", FUND.relay]]) {
    const addr = st.wallets[role].address;
    const bal = await prov.getBalance(addr);
    if (bal >= amt) {
      console.log(`   = ${role} already funded (${fmt(bal)} PAS)`);
      continue;
    }
    const nonce = await prov.getTransactionCount(deployer.address);
    const tx = await deployer.sendTransaction({ to: addr, value: amt, gasLimit: 200_000n, nonce });
    await record(prov, { step: "A.fund", party: `infra:${role}`, action: `fund-${role}`, value: amt, hash: tx.hash });
  }

  // 3. Register the venue (operator=signer=payout=venue wallet) ────────────────
  console.log(`\n3. Register venue`);
  const venues = new ethers.Contract(
    b.venues,
    ["function registerVenue(int32,int32,address,address,string)", "function nextVenueId() view returns (uint64)"],
    V
  );
  if (!st.venueId) {
    const nextId = await venues.nextVenueId();
    const gl = await leanGas(venues.registerVenue, [VENUE_LAT, VENUE_LON, V.address, V.address, "demo://fare-e2e-venue"]);
    const nonce = await prov.getTransactionCount(V.address);
    const tx = await venues.registerVenue(VENUE_LAT, VENUE_LON, V.address, V.address, "demo://fare-e2e-venue", { gasLimit: gl, nonce });
    await record(prov, { step: "A.venue", party: "venue", action: "registerVenue", hash: tx.hash });
    st.venueId = nextId.toString();
    console.log(`   venueId = ${st.venueId}  signer/payout = ${V.address}`);
    saveState(st);
  } else {
    console.log(`   = venue already registered (id ${st.venueId})`);
  }

  // 4. Register the driver ─────────────────────────────────────────────────────
  console.log(`\n4. Register driver`);
  const drivers = new ethers.Contract(
    b.drivers,
    ["function register(string) payable", "function isEligible(address) view returns (bool)"],
    D
  );
  if (!(await drivers.isEligible(D.address))) {
    const gl = await leanGas(drivers.register, ["ipfs://fare-e2e-driver"], { value: 0n });
    const nonce = await prov.getTransactionCount(D.address);
    const tx = await drivers.register("ipfs://fare-e2e-driver", { value: 0n, gasLimit: gl, nonce });
    await record(prov, { step: "A.driver", party: "driver", action: "registerDriver", hash: tx.hash });
  } else {
    console.log(`   = driver already eligible`);
  }
  console.log(`   driver eligible: ${await drivers.isEligible(D.address)}`);

  // 5. Write the venue-node relay .env (profit guard OFF for a gasless demo) ────
  console.log(`\n5. Write venue-node/.env for the relay`);
  const relayEnv = [
    `# Generated by e2e-setup.mjs for the live KS-funded e2e run`,
    `RELAY_PRIVATE_KEY=${st.wallets.relay.privateKey}`,
    `RELAY_RPC_URL=${process.env.TESTNET_RPC || "https://eth-rpc-testnet.polkadot.io/"}`,
    `RELAY_PORT=8788`,
    `ADDRESS_BOOK=../deployed-addresses.json`,
    `ALLOWED_ORIGINS=*`,
    `RATE_MAX=100`,
    `RELAY_PROFIT_GUARD=off`, // sponsor pickup + dropoff regardless of tiny testnet fares
    ``,
  ].join("\n");
  fs.writeFileSync(path.join(ROOT, "venue-node", ".env"), relayEnv);
  console.log(`   wrote venue-node/.env (relay = ${R})`);

  saveState(st);
  console.log(`\n✅ setup complete. venueId=${st.venueId} relay=${R} burner=${st.wallets.burner.address}`);
}

main().catch((e) => {
  console.error("SETUP FAILED:", e?.shortMessage ?? e?.message ?? e);
  process.exit(1);
});
